In [1]:
import h5py
import numpy as np
import matplotlib.pyplot as plt

In [2]:
with h5py.File('simulation.hdf5','r') as hdf:
    ls = hdf.keys()
    print("list of datasets in this file: \n", ls)
    data = hdf.get('Snapshots')
    dataset1 = np.array(data)
    print("shape of dataset1: \n", dataset1.shape)

list of datasets in this file: 
 <KeysViewHDF5 ['Config', 'Groups', 'Header', 'Offsets', 'Parameters', 'Snapshots', 'Trees']>
shape of dataset1: 
 (100,)


In [4]:
dataset1

array(['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18',
       '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28',
       '29', '3', '30', '31', '32', '33', '34', '35', '36', '37', '38',
       '39', '4', '40', '41', '42', '43', '44', '45', '46', '47', '48',
       '49', '5', '50', '51', '52', '53', '54', '55', '56', '57', '58',
       '59', '6', '60', '61', '62', '63', '64', '65', '66', '67', '68',
       '69', '7', '70', '71', '72', '73', '74', '75', '76', '77', '78',
       '79', '8', '80', '81', '82', '83', '84', '85', '86', '87', '88',
       '89', '9', '90', '91', '92', '93', '94', '95', '96', '97', '98',
       '99'], dtype='<U2')

In [5]:
with h5py.File('simulation.hdf5','r') as hdf:
    base_items = list(hdf.items())
    print("items in the base directory", base_items)
    g1 = hdf.get('Snapshots')
    g1_items = list(g1.items())
    print("items in group", g1_items)
    g2 = g1.get('99')
    g2_items = list(g2.items())
    print("items in g1", g2_items)
    halo = g2.get('PartType1')
    halo_items = list(halo.items())
    print("Halos", halo_items)
    ID = halo.get('Coordinates')
    dataset2= np.array(ID)

items in the base directory [('Config', <HDF5 group "/Config" (0 members)>), ('Groups', <HDF5 group "/Groups" (100 members)>), ('Header', <HDF5 group "/Header" (0 members)>), ('Offsets', <HDF5 group "/Offsets" (98 members)>), ('Parameters', <HDF5 group "/Parameters" (0 members)>), ('Snapshots', <HDF5 group "/Snapshots" (100 members)>), ('Trees', <HDF5 group "/Trees" (1 members)>)]
items in group [('0', <HDF5 group "/Snapshots/0" (2 members)>), ('1', <HDF5 group "/Snapshots/1" (2 members)>), ('10', <HDF5 group "/Snapshots/10" (2 members)>), ('11', <HDF5 group "/Snapshots/11" (2 members)>), ('12', <HDF5 group "/Snapshots/12" (2 members)>), ('13', <HDF5 group "/Snapshots/13" (2 members)>), ('14', <HDF5 group "/Snapshots/14" (2 members)>), ('15', <HDF5 group "/Snapshots/15" (2 members)>), ('16', <HDF5 group "/Snapshots/16" (2 members)>), ('17', <HDF5 group "/Snapshots/17" (2 members)>), ('18', <HDF5 group "/Snapshots/18" (2 members)>), ('19', <HDF5 group "/Snapshots/19" (2 members)>), ('2'

In [6]:
dataset2
print(np.shape(dataset2))

(19683000, 3)


In [7]:
with h5py.File('simulation.hdf5','r') as hdf:
    base_items = list(hdf.items())
    print("items in the base directory", base_items)
    g1 = hdf.get('Groups')
    g1_items = list(g1.items())
    print("items in group", g1_items)
    g2 = g1.get('99')
    g2_items = list(g2.items())
    print("items in g1", g2_items)
    halo = g2.get('Subhalo')
    halo_items = list(halo.items())
    print("Halos", halo_items)

items in the base directory [('Config', <HDF5 group "/Config" (0 members)>), ('Groups', <HDF5 group "/Groups" (100 members)>), ('Header', <HDF5 group "/Header" (0 members)>), ('Offsets', <HDF5 group "/Offsets" (98 members)>), ('Parameters', <HDF5 group "/Parameters" (0 members)>), ('Snapshots', <HDF5 group "/Snapshots" (100 members)>), ('Trees', <HDF5 group "/Trees" (1 members)>)]
items in group [('0', <HDF5 group "/Groups/0" (1 members)>), ('1', <HDF5 group "/Groups/1" (1 members)>), ('10', <HDF5 group "/Groups/10" (3 members)>), ('11', <HDF5 group "/Groups/11" (3 members)>), ('12', <HDF5 group "/Groups/12" (3 members)>), ('13', <HDF5 group "/Groups/13" (3 members)>), ('14', <HDF5 group "/Groups/14" (3 members)>), ('15', <HDF5 group "/Groups/15" (3 members)>), ('16', <HDF5 group "/Groups/16" (3 members)>), ('17', <HDF5 group "/Groups/17" (3 members)>), ('18', <HDF5 group "/Groups/18" (3 members)>), ('19', <HDF5 group "/Groups/19" (3 members)>), ('2', <HDF5 group "/Groups/2" (3 members

In [8]:
halo_id = 3000
part_type = 1

with h5py.File('simulation.hdf5','r') as f:
    start = f['/Offsets/99/Group/SnapByType'][halo_id, part_type]
    length = f['/Groups/99/Group/GroupLenType'][halo_id, part_type]

    dm_positions = f['/Snapshots/99/PartType1/Coordinates'][start:start+length,:]
    
    print(dm_positions)

[[ 7630.05037008 17754.20590938 25753.59099645]
 [ 7634.44527592 17755.37991355 25753.97450954]
 [ 7629.00456723 17751.5781142  25752.82771657]
 [ 7628.29018188 17750.7765292  25752.32336329]
 [ 7625.14499965 17758.18315427 25753.06151522]
 [ 7634.41342573 17750.7879333  25758.82589776]
 [ 7633.25038387 17751.53088514 25751.73954628]
 [ 7629.98070992 17751.22247306 25755.16955422]
 [ 7630.42064789 17755.68085487 25755.88273135]
 [ 7633.83938309 17751.89435009 25761.58571921]
 [ 7629.8405228  17761.02960367 25761.4293517 ]
 [ 7625.16226921 17756.24564111 25751.80653396]
 [ 7625.42715212 17759.23991413 25755.91384974]
 [ 7636.61302819 17757.63930442 25759.63760926]
 [ 7635.9074323  17756.35445504 25759.13712183]
 [ 7626.51526273 17758.9193137  25754.74135715]
 [ 7632.01150337 17746.92057043 25757.31418694]
 [ 7635.88927111 17758.75868479 25756.1384629 ]
 [ 7633.0781001  17755.08452936 25753.83268985]
 [ 7625.85024187 17757.81624549 25754.33606207]
 [ 7625.48566619 17750.01971229 25752.78

In [9]:
with h5py.File('simulation.hdf5','r') as f:
    gas_cell_mass = f['/Snapshots/99/PartType1/Potential'][()]
    print(gas_cell_mass)
    #subhalo_size_stars = f['/Groups/99/Subhalos/SubhaloHalfmassRadType'][:,4]

[-3308686.   -3307920.2  -3310257.5  ...   -84379.76   -85486.23
   -67484.76]


In [10]:
pip install illustris_python/

Defaulting to user installation because normal site-packages is not writeable
Processing ./illustris_python
  Preparing metadata (setup.py) ... done
  Created wheel for illustris-python: filename=illustris_python-1.0.0-py3-none-any.whl size=15069 sha256=101f09a234f822819bb22f924f2d976cc3a340a6903c1c1acc74e4c1e27ee1b0
  Stored in directory: /tmp/pip-ephem-wheel-cache-p7he481q/wheels/1f/93/21/82d071861997dfbdd2316009496ad3b800b86a00dd7b025719
Successfully built illustris-python
  Attempting uninstall: illustris-python
    Found existing installation: illustris-python 1.0.0
    Uninstalling illustris-python-1.0.0:
      Successfully uninstalled illustris-python-1.0.0
Note: you may need to restart the kernel to use updated packages.


In [11]:
with h5py.File('simulation.hdf5','r') as hdf:
    base_items = list(hdf.items())
    print("items in the base directory", base_items)
    g1 = hdf.get('Snapshots')
    g1_items = list(g1.items())
    print("items in group", g1_items)
    g2 = g1.get('99')
    g2_items = list(g2.items())
    print("items in g1", g2_items)
    halo = g2.get('Subhalo')
    halo_items = list(halo.items())
    print("Halos", halo_items)
    ID = halo.get('ParticleIDs')
    print(np.shape(ID))

items in the base directory [('Config', <HDF5 group "/Config" (0 members)>), ('Groups', <HDF5 group "/Groups" (100 members)>), ('Header', <HDF5 group "/Header" (0 members)>), ('Offsets', <HDF5 group "/Offsets" (98 members)>), ('Parameters', <HDF5 group "/Parameters" (0 members)>), ('Snapshots', <HDF5 group "/Snapshots" (100 members)>), ('Trees', <HDF5 group "/Trees" (1 members)>)]
items in group [('0', <HDF5 group "/Snapshots/0" (2 members)>), ('1', <HDF5 group "/Snapshots/1" (2 members)>), ('10', <HDF5 group "/Snapshots/10" (2 members)>), ('11', <HDF5 group "/Snapshots/11" (2 members)>), ('12', <HDF5 group "/Snapshots/12" (2 members)>), ('13', <HDF5 group "/Snapshots/13" (2 members)>), ('14', <HDF5 group "/Snapshots/14" (2 members)>), ('15', <HDF5 group "/Snapshots/15" (2 members)>), ('16', <HDF5 group "/Snapshots/16" (2 members)>), ('17', <HDF5 group "/Snapshots/17" (2 members)>), ('18', <HDF5 group "/Snapshots/18" (2 members)>), ('19', <HDF5 group "/Snapshots/19" (2 members)>), ('2'

AttributeError: 'NoneType' object has no attribute 'items'